### ISSUE TITLE
Add p2h/beeline wrapper to reload hive partitions

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/python_mozetl#16]
We can (and should, imo) invoke parquet2hive in the context of a job to load new partitions into hive after write, instead of waiting for a cron to run: e.g. https://github.com/mozilla/telemetry-airflow/blob/master/jobs/longitudinal_view.sh#L21

I propose we add a wrapper to the python_etl library to improve the experience for job authors.

**Comment by vitillo** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1356703.
