### ISSUE TITLE
Flake8 no longer enforced by travis

### ISSUE THREAD

**Issue by harterrt** [mozilla/python_mozetl#162]
Running tox locally shows some flake8 violations. Looking at the [most recent CI run](https://travis-ci.org/mozilla/python_mozetl), it looks like flak8 is no longer tested.

**Comment by harterrt** [comment]
@acmiyaguchi FYI

**Comment by acmiyaguchi** [comment]
This has cause some recent outages on datasets due to broken imports. Patch on the way.

**Comment by harterrt** [comment]
FYI: I ran into this recently with Docere. I fixed it by explicitly setting explicit `env` for each tox environment. See [this .travis.yml](https://github.com/harterrt/docere/blob/master/.travis.yml).

**Comment by acmiyaguchi** [comment]
That's how I managed to solve it, it's weird that it's unset in Travis.
