### ISSUE TITLE
`taar` tests write json to root directory

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/python_mozetl#219]
`taar` is a module that generally interacts with `addons.mozilla.org`. There are several submodules that test their functionality by processing the resulting json in a testing context. The output of these jobs should change to a temporary directory or clean up in order to avoid cluttering the main project folder.

**Comment by crankycoder** [comment]
@acmiyaguchi this issue should be resolved now.

**Comment by crankycoder** [comment]
@acmiyaguchi this bug is fixed
