### ISSUE TITLE
Base add-ons query for taar_locale should restrict to 1 row per client

### ISSUE THREAD

**Issue by dzeber** [mozilla/python_mozetl#280]
https://github.com/mozilla/python_mozetl/blob/09a64456ff290599fd5d7b1892e5704c9582eb15/mozetl/taar/taar_locale.py#L41-L49

The base query in `get_addons()` filters by `channel` and `app_name` but otherwise includes all rows.

Since `clients_daily` has 1 row per clientID per submission date, this means that we are double-counting clients. Eg., if a client was active on 5 different dates, they would have 5 rows in the dataset and contribute up to 5 to the `pair_cnts` for each of their add-ons. This query should probably select the row with the most recent submission date for each clientID.

Also, since `clients_daily` ranges back to early 2016, the query pulls in add-on installs over that entire time period. It should probably be limited to recent activity by `submission_date_s3` (say, to the last 3 months) for efficiency and relevance.

**Comment by mlopatka** [comment]
Nice catch @dzeber 
This issue also affects the [similarity job](https://github.com/mozilla/python_mozetl/blob/master/mozetl/taar/taar_similarity.py) and likely all other taar ETL that have been ported from longitudinal to clients_daily.
