### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by harterrt** [mozilla/python_mozetl#31]
Looks like [recent test runs are failing](https://travis-ci.org/mozilla/python_mozetl/builds). I tried reverting recent commits and running tests locally, but this didn't fix the issue. This suggests the error is caused by some upstream change in a dependency.

Frank it looks like the tab spinner tests are the only tests affected. Can you take an initial look?

**Comment by fbertsch** [comment]
Looks like another instance of Bug 1363934. Nothing to do but wait until it's fixed.

**Comment by acmiyaguchi** [comment]
From the looks of recent test runs, this looks like it's been resolved.
