### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by harterrt** [mozilla/python_mozetl#34]
Looks like the tests are [failing on master](https://travis-ci.org/mozilla/python_mozetl/builds/231195163). Anthony, looks like it's the topline dashboard (or some change in the moto module). Can you take a look?

**Comment by acmiyaguchi** [comment]
I made a [pull request to fix this upstream](https://github.com/spulec/moto/pull/950). I can add mock as a dependency and remove some of the monkey patching I wrote to get around bad library interactions.

**Comment by acmiyaguchi** [comment]
There's still one failure left, which is probably related to toLocalIterator.
