### ISSUE TITLE
Standardize CLI entrypoint for airflow jobs

### ISSUE THREAD

**Issue by harterrt** [mozilla/python_mozetl#38]
We have a few different access points configured for different jobs [1]. We should have a single entrypoint that reads common environment variables, starts a spark context, and launches the proper job. 

[1] Examples:
https://github.com/mozilla/python_mozetl/blob/master/scheduling/pulse.py
https://github.com/mozilla/python_mozetl/blob/master/scheduling/tab_spinner.py
https://github.com/mozilla/python_mozetl/blob/master/mozetl/churn/churn.py#L648

**Comment by acmiyaguchi** [comment]
I think this take the following form:

* Using options and required options over positional arguments
* Add job to an `entry_point` object
* A common entry point in `telemetry-airflow/jobs`

**Comment by acmiyaguchi** [comment]
There are some subtle side-effects of using automatic environment variables that should be documented.

There is an option called `auto_envvar_prefix` in commands that wraps all `click.options` with the ability to read the value from the environment. This is done by taking the name of the prefix and appending the name of the option. In addition, if the command is part of a group (the mozetl entry point), then the name of the subcommand is appended to prefix. For example, the `date` option from the `churn` job would read the value `MOZETL_CHURN_DATE` from the environment if `auto_envvar_prefix="MOZETL"`.

A utility function could be added to aid in the construction of the environment variables in the airflow dag.

```
def mozetl_envvar(command, env):
    # TODO: also include command name as an environment variable, for mozetl job script
    return {"MOZETL_{}_{}".format(command, key): value for key, value in env}
```

**Comment by acmiyaguchi** [comment]
The `mozetl-submit` can be added to the `setup.py` with custom build steps. It might also be useful for building the docker container and running tests.

**Comment by acmiyaguchi** [comment]
This has been merged in, now all is left to do is to add more jobs to it.
