### ISSUE TITLE
Move activity-date transmission lag to a constants file

### ISSUE THREAD

**Issue by SamPenrose** [mozilla/python_mozetl#50]
Because multiple jobs will invoke a lag heuristic when aggregating data by client activity (e.g. subsessionStartDate), let's separate policy from mechanism.

C.f. https://github.com/mozilla/python_mozetl/blob/master/mozetl/churn/churn.py#L7

**Comment by harterrt** [comment]
Hey @SamPenrose, what's the priority on this?

**Comment by SamPenrose** [comment]
Low, I just wanted to make a note of it. I'll submit a PR at some point unless someone has a reason for me not to.
