### ISSUE TITLE
containers_shield hive table doesn't exist?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/python_mozetl#53]
If https://github.com/mozilla/python_mozetl/blob/master/mozetl/testpilot/containers.py is running correctly, I would expect to be able to `SELECT * FROM containers_shield` in STMO. But, I get:

`Error running query: line 14:10: Table hive.default.containers_shield does not exist`

**Comment by harterrt** [comment]
Ah, we never asked ops to load that dataset into re:dash. The data is there, we just need to file a bug as described in step three of [this doc](https://mozilla.github.io/firefox-data-docs/cookbooks/create_a_dataset.html).

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1373711
