### ISSUE TITLE
Add pyup.io bot to this repo

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/python_mozetl#60]
This seems to be the standard procedure for other repos, we should consider doing it here as well.

**Comment by acmiyaguchi** [comment]
I don't like the amount of noise that the bot produces proportional to the value it adds. It also seems a bit cargo cultish, but I recognize the problems it's trying to solve.

The dependencies used in this repository don't change often -- the only dependency that necessarily needs to be up-to-date is `python_moztelemetry`,  a package that is rebuilt on bootstrap regardless. The other large dependency,`pyspark`, is determined by the current stable EMR version defined in our bootstrap script and isn't specifically defined in `setup.py`. 

If standard procedure for python packages that we build includes dependency pinning, this might be worth a look at a low update frequency (montly). Dependency pinning aids reproducible deployments, so if we do add dependency pinning we may want to consider a deployment route from `python_mozetl` to `telemetry-airflow` that is more reliant on packaging. Deployments might become a bit more involved than merging a PR.

**Comment by mreid-moz** [comment]
I totally agree that pyup makes a lot of noise, and is kind of cumbersome.

The main argument I'm convinced by is keeping up with security updates. For that reason alone, I'm inclined to add it to the repo and tolerate the pyup spam.

**Comment by harterrt** [comment]
I'm still a neophyte to python development, but I don't see how this could improve security. It looks like all of our dependencies are unconstrained by version. What does the bot actually do to include security updates?

**Comment by mreid-moz** [comment]
Let's not apply pyup until/unless we start pinning dependency versions. At that point, we can also limit it to only address security issues similar to [this PR](https://github.com/mozilla/missioncontrol/pull/82).
