### ISSUE TITLE
I just force-pushed my local master to this repo. :(

### ISSUE THREAD

**Issue by groovecoder** [mozilla/python_mozetl#74]
I accidentally force-pushed my local master at f85ffda to this repo. Can someone who had the previous latest master re-push `master` up here?

**Comment by SamPenrose** [comment]
Someone want to merge my last PR, which undoes this?

**Comment by harterrt** [comment]
Merged https://github.com/mozilla/python_mozetl/pull/75 so this should be resolved. For the record it looks like this wasn't a force push, just an extra commit on master. Thanks all!
