### ISSUE TITLE
Add content to wiki

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/python_mozetl#86]
There should be enough content on the wiki to address all parts of adding a new job to python_mozetl. This will be used as a rough draft for addition in the firefox data docs.
 
- [x] what is this repository
- [ ] what is an etl job
- [ ] why python and pyspark
- [ ] how it works
- [ ] repository organization
- [ ] notebook to job
- [ ] adding a job
- [ ] writing tests
- [ ] logging (what, where, when, why)
- [ ] `mozetl-submit`
- [ ] scheduling (airflow, atmo)
- [ ] reference materials (click, pyspark, boto, pytest)
- [ ] contribution

**Comment by acmiyaguchi** [comment]
- [ ] what is this repository
- [ ] what is an etl job
- [ ] why python and pyspark
- [ ] how it works
- [ ] repository organization
- [ ] notebook to job
- [ ] adding a job
- [ ] writing tests
- [ ] logging (what, where, when, why)
- [ ] `mozetl-submit`
- [ ] scheduling (airflow, atmo)
- [ ] reference materials (click, pyspark, boto, pytest)
- [ ] contribution

**Comment by harterrt** [comment]
Feel free to add these documents piecemeal to firefox-data-docs. As a general rule of thumb, firefox-data-docs should host high-level conceptual documentation that's unlikely to change with the code (e.g. main_summary has one row per ping). Anything more specific to this tool should live in this repository with the code. 

At first glance, most of these topics look like they belong in this repo. Some can be duplicated in the firefox-data-docs.

I usually advise against a wiki. In my experience, version controlled markdown documents are much easier to reason about.

**Comment by acmiyaguchi** [comment]
On a second thought, the content on the wiki should be geared towards example usages. This issue isn't tracking anything that is really actionable.
